// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDIrAXpTWvhqH1fdAoxj2FVFsiEnEKx00',
    appId: '1:209363729098:web:50924687ab8652fb339233',
    messagingSenderId: '209363729098',
    projectId: 'fir-input-61e68',
    authDomain: 'fir-input-61e68.firebaseapp.com',
    databaseURL: 'https://fir-input-61e68-default-rtdb.firebaseio.com',
    storageBucket: 'fir-input-61e68.firebasestorage.app',
    measurementId: 'G-X0WKL1HEFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_qosFXnnlQTrIHvD55ngBGbT-GgjgvA',
    appId: '1:209363729098:android:2b010da6a93ef516339233',
    messagingSenderId: '209363729098',
    projectId: 'fir-input-61e68',
    databaseURL: 'https://fir-input-61e68-default-rtdb.firebaseio.com',
    storageBucket: 'fir-input-61e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMQdWo4-HGOF8Rj9TggFkauy9m8eVkDU',
    appId: '1:209363729098:ios:dcba89308db3db18339233',
    messagingSenderId: '209363729098',
    projectId: 'fir-input-61e68',
    databaseURL: 'https://fir-input-61e68-default-rtdb.firebaseio.com',
    storageBucket: 'fir-input-61e68.firebasestorage.app',
    iosBundleId: 'com.example.sprout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfMQdWo4-HGOF8Rj9TggFkauy9m8eVkDU',
    appId: '1:209363729098:ios:09f8e3d20fe04d14339233',
    messagingSenderId: '209363729098',
    projectId: 'fir-input-61e68',
    databaseURL: 'https://fir-input-61e68-default-rtdb.firebaseio.com',
    storageBucket: 'fir-input-61e68.firebasestorage.app',
    iosBundleId: 'com.example.sprout',
  );
}